"""
agents/quant_researcher/codegen.py -- materializes a promoted
StrategySpec into an actual, reviewable Python module + a matching test
file, written by plain open(...).write() calls -- never eval/exec of
anything the research engine produced, the same discipline
agents/dev_agent/patcher.py already holds itself to for LLM output. The
generated module is a thin, deterministic template: it defines the
StrategySpec as data and delegates all behavior to strategy_runner.py's
existing interpreter, so promoting a new strategy is never "new logic
appears," only "new parameters get materialized."
"""
from .strategy_spec import StrategySpec

MODULE_TEMPLATE = '''"""
{module_doc}

Generated by agents.quant_researcher.codegen -- do not hand-edit the
SPEC below; evolve it through another research cycle instead, so the
change stays recorded in Strategy Evolution Memory.
"""
from agents.quant_researcher.strategy_spec import StrategySpec

SPEC = StrategySpec(
    name={name!r},
    symbol={symbol!r},
    hypothesis_id={hypothesis_id!r},
    features={features!r},
    thresholds={thresholds!r},
    direction={direction!r},
    target_points={target_points!r},
    stop_points={stop_points!r},
    max_hold_bars={max_hold_bars!r},
    params={params!r},
)


def run(candles, cycles=None, *, expiry_dates=None):
    """Runs this promoted strategy's SPEC against the given market data
    via the shared generic interpreter -- returns the same trade-dict
    shape every engine in this repo produces."""
    from agents.quant_researcher import strategy_runner
    return strategy_runner.run_strategy(SPEC, candles, cycles, expiry_dates=expiry_dates)
'''

TEST_TEMPLATE = '''"""Generated regression test for {module_name} -- confirms the promoted
SPEC loads and the module's run() delegates to the shared interpreter
without error on an empty candle set (a real backtest already ran during
promotion; this is a load-bearing smoke test, not a re-validation)."""
import pandas as pd

from {module_name} import SPEC, run


def test_spec_has_expected_symbol_and_hypothesis():
    assert SPEC.symbol == {symbol!r}
    assert SPEC.hypothesis_id == {hypothesis_id!r}


def test_run_on_empty_candles_returns_no_trades():
    empty = pd.DataFrame(columns=["datetime", "open", "high", "low", "close"])
    assert run(empty) == []
'''


def generate_module(spec: StrategySpec) -> str:
    doc = f"Promoted strategy: {spec.name} (hypothesis: {spec.hypothesis_id}, symbol: {spec.symbol})."
    return MODULE_TEMPLATE.format(
        module_doc=doc, name=spec.name, symbol=spec.symbol, hypothesis_id=spec.hypothesis_id,
        features=spec.features, thresholds=spec.thresholds, direction=spec.direction,
        target_points=spec.target_points, stop_points=spec.stop_points,
        max_hold_bars=spec.max_hold_bars, params=spec.params,
    )


def generate_test(spec: StrategySpec, module_name: str) -> str:
    return TEST_TEMPLATE.format(module_name=module_name, symbol=spec.symbol, hypothesis_id=spec.hypothesis_id)


def _safe_slug(name: str) -> str:
    slug = "".join(c if c.isalnum() else "_" for c in name).lower().strip("_")
    return slug or "strategy"


def file_paths(spec: StrategySpec, *, strategies_dir: str) -> tuple:
    """Returns (module_relpath, module_import_name, test_relpath)."""
    safe_name = _safe_slug(spec.name)
    module_relpath = f"{strategies_dir}/{safe_name}.py"
    module_import_name = f"{strategies_dir}.{safe_name}"
    test_relpath = f"{strategies_dir}/test_{safe_name}.py"
    return module_relpath, module_import_name, test_relpath
